name: CI/CD - Deploy to Elastic Beanstalk

on:
  push:
    branches: [ "main" ]   # Deploy only on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          SECRET_KEY: testsecret
          DEBUG: True
          POSTGRES_SSLMODE: disable
        run: |
          python manage.py migrate --noinput
          pytest --maxfail=1 --disable-warnings -q

      - name: Create deployment package
        run: |
          zip -r deploy.zip . \
            -x "*.git*" \
              "*__pycache__*" \
              "*.pytest_cache*" \
              "docker-compose.yml" \
              ".env*" \
              ".gitignore" \
              ".dockerignore" \
              "README.md" \
              "sample.env" \
              "deploy.py" \
              "pytest.ini" \
              "wait_for_db.py"

      - name: Show zip contents
        run: unzip -l deploy.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} #Updated secret

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          version_label: github-${{ github.run_number }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
